[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Ensure automatic deployments from both main branch and lovable changes
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
